### ISSUE TITLE
fixedbb/cmlm

### ISSUE THREAD

**Issue by QUEST2179** [BytedProtein/ByProt#17]
with updated version, a new error occurs

  File "C:\Users\structure\ByProt\testDesignLM.py", line 189, in DesignbyLM
    designer = Designer(experiment_path=exp_path, cfg=cfg)
  File "C:\Users\structure\ByProt\byprot\tasks\fixedbb\designer.py", line 59, in __init__
    self._initialize()
  File "C:\Users\structure\ByProt\byprot\tasks\fixedbb\designer.py", line 62, in _initialize
    pl_task, exp_cfg = utils.load_from_experiment(
  File "C:\Users\structure\ByProt\byprot\utils\__init__.py", line 63, in load_from_experiment
    pl_module = instantiate_from_config(cfg=cfg.task, group='task', model=cfg.model)
  File "C:\Users\structure\ByProt\byprot\utils\config.py", line 110, in instantiate_from_config
    raise KeyError(
KeyError: 'fixedbb/cmlm is not a registered <task> class [dict_keys([])].'

**Comment by zhengzx-nlp** [comment]
this seems strange. I just uploaded a scripts to design for a pdb folder. can you try it at `scripts/design_pdb.*`?

**Comment by QUEST2179** [comment]
same error.

python design_pdb.py --experiment_path models/lm_design_esm2_650m_multichain --ckpt "best.ckpt" --pdb_dir test --out_dir output --seed 42 --num_seqs 1 --temperature 0.1 --max_iter 5
Namespace(seed=42, num_seqs=1, experiment_path='models/lm_design_esm2_650m_multichain', ckpt='best.ckpt', pdb_dir='test', out_dir='output', temperature=0.1, strategy='denoise', max_iter=5)
Global seed set to 42
Traceback (most recent call last):
  File "C:\Users\structure\ByProt\design_pdb.py", line 140, in <module>
    main()
  File "C:\Users\structure\ByProt\design_pdb.py", line 136, in main
    generate(args)
  File "C:\Users\structure\ByProt\design_pdb.py", line 84, in generate
    model, alphabet, collater, generator = setup_generation(args, args.ckpt)
  File "C:\Users\structure\ByProt\design_pdb.py", line 39, in setup_generation
    pl_module, exp_cfg = utils.load_from_experiment(
  File "C:\Users\structure\ByProt\byprot\utils\__init__.py", line 63, in load_from_experiment
    pl_module = instantiate_from_config(cfg=cfg.task, group='task', model=cfg.model)
  File "C:\Users\structure\ByProt\byprot\utils\config.py", line 110, in instantiate_from_config
    raise KeyError(
KeyError: 'fixedbb/cmlm is not a registered <task> class [dict_keys([])].'
